### ISSUE TITLE
Cant import the module Using Angular 4

### ISSUE THREAD

**Issue by theoscat** [gmazzamuto/ng2-google-charts#32]
Hi,

I think im missing something.
I've tried to import the module but i keep getting a 404 when i load my ui =>
`Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-google-charts
	Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-google-charts
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1199:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3000/ng2-google-charts as "ng2-google-charts" from http://localhost:3000/app/logs/logs.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1199:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3000/ng2-google-charts as "ng2-google-charts" from http://localhost:3000/app/logs/logs.module.js`

here's my import 

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { Ng2GoogleChartsModule } from 'ng2-google-charts';

import { LogsComponent } from './logs.component';
import { RawLogsComponent } from './raw-logs/raw-logs.component';

import { LogsService } from './shared/logs.service';

@NgModule({
  imports: [CommonModule, Ng2GoogleChartsModule],
  declarations: [ LogsComponent, RawLogsComponent  ],
  providers: [ LogsService ],
  bootstrap: [  ]
})
export class LogsModule { }`

I'm using Angular 4 and i would like to insert some charts in my ui.

Thanks,

Théo

**Comment by dspachos** [comment]
Hmm..Followed the instruction and worked only after I imported in my custom.module.ts
```
import { Ng2GoogleChartsModule } from 'ng2-google-charts';

...

@NgModule({
  imports: [
...
    Ng2GoogleChartsModule
  ],

```

**Comment by theoscat** [comment]
Hi,
I think i was missing something previously.
Since then i might have found the solution. I didnt work on that since my question but i will update as soon as i try again.


Theo
